apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hive-svc","namespace":"default"},"spec":{"ports":[{"port":9090,"protocol":"TCP","targetPort":80}],"selector":{"app":"hive"}}}
  creationTimestamp: "2023-01-03T09:01:22Z"
  name: hive-svc
  namespace: default
  resourceVersion: "511"
  uid: 59793ee9-faf1-4b76-acd8-7d2743747861
spec:
  clusterIP: 10.111.190.150
  clusterIPs:
  - 10.111.190.150
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  selector:
    app: hive
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
