apiVersion: v1
kind: Pod           
metadata:
  name: webserver 
  labels:
     zone: pod
     versions: v1
spec: 
  containers:
  - name: webserver
    image: nginx:latest
    ports: 
    - containerPort: 80
